### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by geosmall** [avtehnik/RTD2662#1]
What toolchain is needed to compile this code?

**Comment by avtehnik** [comment]
I believe http://www.keil.com must do it.
Some people there http://tech.mattmillman.com/lcd/rovatools/ in comments says about this

**Comment by ghent360** [comment]
You need the Keil 8051 toolchain (uVision 4 or 5). The open the .uv2 project file and build it.

**Comment by goudon007** [comment]
I tried to build it with Keil uVision 4.
I get this error, can somebody help me have a working source code.
![image](https://user-images.githubusercontent.com/33927810/33370590-4b63bcd8-d4f8-11e7-8702-7989260a2594.png)

**Comment by floppes** [comment]
The warnings can be ignored, but the fatal error prevents compilation. You have the trial version where the output file size is limited. In order to be able to compile the code, you need a licensed version of uVision.

**Comment by SergeyBokhantsev** [comment]
Hi @avtehnik, could you please advice where/how to define the panel I want to use?
I want to compile for the N070ICG-LD1 1280x800 LVDS panel (on PCB800099)
Thx!

**Comment by lochoang75** [comment]
You can create new file and declare it in panel.h

**Comment by geosmall** [comment]
Closed
