### ISSUE TITLE
ACC trigger help

### ISSUE THREAD

**Issue by Mendilli2** [avtehnik/RTD2662#2]
Hi, I have successfully compiled the code and made a at070tn90 lcd work with pcb800099 board, my issue is I can not make the ACC trigger work which changes the input source to AV1 or AV2 when power (like car reversing 12v) applied to this ACC pin, I can not find the corresponding function or code piece inside the whole source code, can anyone help me

**Comment by specadmin** [comment]
- все Hi,I don't remember exactly, since it was too long ago. However RTD2662 has internal multiplexor for four AV sources: AV1, AV2, AV3 and AV4. Two last signals are available on S-video inputs.As far, as i remember, i was successfully receving video thru AV2, AV3 and AV4 pins. And had unknown troubles with AV1. I have not solved the problem then.Try to use AV3 or AV4 instead of AV1. Perhaps this will help you. 26.09.2024, 19:05, "Mendilli2" ***@***.***>: Hi, I have successfully compiled the code and made a at070tn90 lcd work with pcb800099 board, my issue is I can not make the ACC trigger work which changes the input source to AV1 or AV2 when power (like car reversing 12v) applied to this ACC pin, I can not find the corresponding function or code piece inside the whole source code, can anyone help me—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Mendilli2** [comment]
Thank you for your answer, but I think my problem is just about the code,
if acc pin works I should see the source change even if I dont get an
image, when I apply power to acc pin just nothing happens, I believe there
must be a function in source code to  enable it or I should add some code
from scratch to enable it

27 Eyl 2024 Cum 18:06 tarihinde Anton Rezanov ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
I am not sure but ın some forum sites it is sad to be pin 101 (P5D7)

27 Eyl 2024 Cum 20:03 tarihinde Anton Rezanov ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
I am running a car display project, In my car there is a wire which outputs
12v when reverse gear is activated, this wire is connected to this acc pin
and when the car is reversed the back up camera (av1 or av2) is automaticly
activated on the display, and when the car is back to normal gear display
returns to previous source (hdmi, vga etc),

I am currently using this system but I am having some other issues So I
want to custoomize the firmware just as I needed but I am stuck at this acc
pin issue

27 Eyl 2024 Cum 20:23 tarihinde Anton Rezanov ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
I am currently using a pcb800099 board with this acc pin connected to
reverse wire of my car, I ensure you it definetely works

27 Eyl 2024 Cum 21:13 tarihinde Anton Rezanov ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
I need a code piece which will check if this pin is HIGH or LOW, if it is
HIGH av1 or av2 will be displayed, when it is LOW previous source will be
displayed, I just dont know how to build the code  to access this pin in
keil

27 Eyl 2024 Cum 21:39 tarihinde Murat Mendillioğlu ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
As you see in this schematic pin101 ie axactly do what you decribed, it is
designed to be a voltage detector with a 3v3 pullup resitor

27 Eyl 2024 Cum 21:43 tarihinde Murat Mendillioğlu ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
27 Eyl 2024 Cum 21:54 tarihinde Murat Mendillioğlu ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
Hi again it seems you are right about the issues about av1 and av2 sources,
I can not get picture when I manually select av1 or av2, can you guide me
how to edit the firmware to use the av3 and avd please

27 Eyl 2024 Cum 21:55 tarihinde Murat Mendillioğlu ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
Sorry for distırbing you but it seems av1 and av2 is ok. My av source
device turned out to faulty.

I need to find out the pin number of the acc pin shown in the picture, I
altered the code to change input source if pin101 is LOW (low actually
means high because of pullup resistors on the pcb), it works, when I alter
the code to check if it is HIGH it does not work, I aplied 12v but nothing
happened, that means this pin used for another purpose

Do you know a way how to identify pin numbers on the pcb

29 Eyl 2024 Paz 14:33 tarihinde Murat Mendillioğlu ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
30 Eyl 2024 Pzt 19:25 tarihinde Murat Mendillioğlu ***@***.***>
şunu yazdı:

**Comment by Mendilli2** [comment]
Ok, some progress here, the acc pin number is _PIN_101 or _MCU_PORT57 indeed, By default it is HIGH because of internal pullup, when you apply power it goes LOW, problem was feeding this pin with 5v. It seems 5v is not enough to change the state of the pin to LOW (use 12v)

Not perfect but this seems to work

PCB800099.h file
#define _PIN_101 (0 & 0x07) // 0 ~ 4 (0: P5D7i, 1: P5D7o, 2: P5D7o, 3: PWM5, 4: TCON[0]) //(change this line)

#define _ACC_PIN (_MCU_PORT57) // (add this line)

Main.h file
void CMainUserInitial();
void CMainSystemInitial(void);
void ACCChangeSource(void); //(add this line)
void DbgLed(unsigned char ucCount);

Main.c file
void main(void)
{
CMainSystemInitial();
CUartSendString("Begin...\n");
do
{
CMiscIspDebugProc();
CTimerHandler();
CKeyHandler();
CModeHandler();
COsdHandler();
ACCChangeSource(); //(add this line)
}while(_TRUE);
}

void ACCChangeSource(void) { // (add this function)

if (!_ACC_PIN && _GET_INPUT_SOURCE() == _SOURCE_VGA)
{
switch(_GET_INPUT_SOURCE())
{
case _SOURCE_VGA: _SET_INPUT_SOURCE(_SOURCE_VIDEO_SV);
default: break;
}
COsdDispOsdTimerEvent();
ucOsdEventMsg = _CHANGE_SOURCE_MSG;
}
else if (_ACC_PIN && _GET_INPUT_SOURCE() == _SOURCE_VIDEO_SV)
{
switch(_GET_INPUT_SOURCE())
{
case _SOURCE_VIDEO_SV: _SET_INPUT_SOURCE(_SOURCE_VGA);
default: break;
}
COsdDispOsdTimerEvent();
ucOsdEventMsg = _CHANGE_SOURCE_MSG;
}
}

**Comment by Mendilli2** [comment]
Problem solved
